version: '3.7'

services:

    client:
        build:
            context: ./frontend
            dockerfile: Dockerfile-prod
        ports:
            - "8080:8080"
        volumes: 
            - ./frontend:/app
            - /app/node_modules
        networks:
            - frontend

    mongodb:
        image: mongo
        container_name: mongo
        restart: unless-stopped
        command: mongod --auth
        environment:
            MONGO_INITDB_ROOT_USERNAME: "admin"
            MONGO_INITDB_ROOT_PASSWORD: "password"
            MONGO_INITDB_DATABASE: webapp
            MONGODB_DATA_DIR: /data/db
        volumes:
        - mongodbdata:/data/db
        networks:
        - backend

    api:
        build: 
            context: ./backend
            dockerfile: Dockerfile
        command: gunicorn --bind 0.0.0.0:8081 app:app
        ports:
            - "8081:8081"
        environment:
            MONGODB_HOST: mongodb
            MONGODB_USERNAME: "apiuser"
            MONGODB_PASSWORD: "apipassword"
            JWT_SECRET_KEY: "t1NP63m4wnBg6nyHYKfmc2TpCOGI4nss"
            MAIL_SERVER: "localhost"
            MAIL_PORT: "1025"
            MAIL_USERNAME: "support@koreascoring.com"
            MAIL_PASSWORD: ""
        volumes:
            - appdata:/var/www/
        depends_on: 
            - mongodb
        networks:
            - frontend
            - backend

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge
volumes:
    mongodbdata:
        driver: local
    appdata:
        driver: local